#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoint.gateway.enabled: true

#Logging
logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

spring:
  application.name: api-gateway
  cloud:
    gateway:
      #Filter to avoid Multiple CORS headers
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      #General CORS configuration for Gateway
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8100"
            allowedHeaders: "*"
            allowedMethods: "*"
      discovery.locator.enabled: true
      routes:
        #Workshop service routes
        - id: workshop-service
          uri: lb://workshop-service
          predicates:
            Path=/api/v1/workshop/**
          filters:
            - AuthFilter
        #Auth route
        - id: sign-in-service
          uri: lb://manager-service
          predicates:
            Path=/api/v1/auth/signIn
        #Manager service routes
        - id: manager-service
          uri: lb://manager-service
          predicates:
            Path=/api/v1/manage/**
          filters:
            - AuthFilter
        #Eureka server routes
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            Path=/eureka/web
          filters:
            - SetPath=/
            - AuthFilter
        #Eureka static resources routes
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
          filters:
            - AuthFilter
